# Equilibrium Temperature Distributions

### Authors

Ansh Gandhi, Krrish Kainth, FNU Kalkin

### Division of Labor

|Name|Task|
|----|----|
|Ansh||
|Krrish||
|Kalkin||

### Math Work

Linear Albebra!

In [79]:
import numpy as np
from scipy.linalg import lu_factor
from sympy import Matrix

In [80]:
def solveTempEq(size, lTemp, uTemp, rTemp, dTemp):
    C = np.zeros((size*size, size*size))
    b = np.zeros(size*size)
    for r in range(size):
        for c in range(size):
            ptNum = findPtNum(r, c, size)
            if c - 1 != -1:
                C[ptNum][ptNum - 1] = 1
            else:
                b[ptNum] += lTemp
            if r - 1 != -1:
                C[ptNum][ptNum - size] = 1
            else:
                b[ptNum] += uTemp
            if c + 1 != size:
                C[ptNum][ptNum + 1] = 1
            else:
                b[ptNum] += rTemp
            if r + 1 != size:
                C[ptNum][ptNum + size] = 1
            else:
                b[ptNum] += dTemp
    print(C)
    return np.linalg.solve(4 * np.identity(size * size) - C, b)

def findPtNum(row, col, size):
    return size * row + col

In [81]:
print(solveTempEq(2, 10, 30, 0, 20))

[[0. 1. 1. 0.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 1. 0.]]
[17.5 15.  15.  12.5]


## Question 1

Solve the following system by row reduction:
![](https://cdn.discordapp.com/attachments/860730627862429727/958443092137103390/unknown.png)

![](https://cdn.discordapp.com/attachments/860730627862429727/958806269794349086/unknown.png)

![](https://cdn.discordapp.com/attachments/860730627862429727/958809485810475018/unknown.png)

![](https://cdn.discordapp.com/attachments/860730627862429727/958809604869996604/unknown.png)

In [82]:
C = Matrix([[0, 1, 1, 0],
            [1, 0, 0, 1],
            [1, 0, 0, 1],
            [0, 1, 1, 0]])
print("C = ")
C


C = 


Matrix([
[0, 1, 1, 0],
[1, 0, 0, 1],
[1, 0, 0, 1],
[0, 1, 1, 0]])

In [83]:
I = Matrix([[1, 0, 0, 0],
            [0, 1, 0, 0],
            [0, 0, 1, 0],
            [0, 0, 0, 1]])
A = 4 * I - C
print("A = ")
A

A = 


Matrix([
[ 4, -1, -1,  0],
[-1,  4,  0, -1],
[-1,  0,  4, -1],
[ 0, -1, -1,  4]])

In [84]:
M = M.col_insert(M.shape[0], Matrix([40, 30, 30, 20]))
print("Augmented Matrix:")
M

Augmented Matrix:


Matrix([
[ 4, -1, -1,  0, 40, 40],
[-1,  4,  0, -1, 30, 30],
[-1,  0,  4, -1, 30, 30],
[ 0, -1, -1,  4, 20, 20]])

In [85]:
print("Row Reduced Echelon Form:")
M.rref()[0]

Row Reduced Echelon Form:


Matrix([
[1, 0, 0, 0, 35/2, 35/2],
[0, 1, 0, 0,   15,   15],
[0, 0, 1, 0,   15,   15],
[0, 0, 0, 1, 25/2, 25/2]])

In [86]:
x = M.rref()[0].col(M.shape[0])
print('x = ')
x

x = 


Matrix([
[35/2],
[  15],
[  15],
[25/2]])

## Question 2

Find A, the inverse of A, and x for the above system of equations. Confirm that your answer matches that of Question 1.

In [87]:
C = np.matrix([[0, 1, 1, 0], [1, 0, 0, 1], [1, 0, 0, 1], [0, 1, 1, 0]])
b = np.array([[40], [30], [30], [20]])
A = 4 * np.identity(4) - C
print(A)

[[ 4. -1. -1.  0.]
 [-1.  4.  0. -1.]
 [-1.  0.  4. -1.]
 [ 0. -1. -1.  4.]]


In [88]:
AInv = np.linalg.inv(A)
print(AInv)

[[0.29166667 0.08333333 0.08333333 0.04166667]
 [0.08333333 0.29166667 0.04166667 0.08333333]
 [0.08333333 0.04166667 0.29166667 0.08333333]
 [0.04166667 0.08333333 0.08333333 0.29166667]]


In [89]:
x = AInv * b
print(x)

[[17.5]
 [15. ]
 [15. ]
 [12.5]]


# Question 3
Suppose that the external temperature at the top of the plate changes to 50&deg;. Use results from 
Question 2 to find the new equilibrium temperature distribution. 

In [90]:
b = np.array([[60], [50], [30], [20]])
x = AInv * b
print(x)

[[25. ]
 [22.5]
 [17.5]
 [15. ]]


# Question 4
Do an LU decomposition of _A_ above. Use it to solve the original system and the system with altered external temperatures. Confirm your earlier results. 

# Question 5
A finer grid should give a better approximation of the equilibrium temperatures. Consider the grid in Figure 3 on the following page. Now there are 25 grid points inside the plate, so we now have a system of 25 equations in 25 unknowns. The matrix _C_ and the vector **b** below apply to this situation.

Find the temperature distribution in this case with the original external temperatures by either finding $(4I-C)^{-1}$ or by using the LU factorization.